name: Example Workflow

on: [push]

jobs:
  checkout-job:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a command
        run: echo "Hello from github-runner!"

  build-job:
    runs-on: [self-hosted]
    steps:
        - name: maven-compile
          run: mvn compile
        - name: maven test
          run: mvn test
        - name: maven package
          run: mvn package
    needs: [checkout-job]

          