name: using with command
on: [push]
jobs:
  simple-action:
   runs-on: ubuntu-latest
   steps:
    - name: Simple JS Action 
      id: hello-world-greet
      uses: actions/hello-world-javascript-action@main
      with:
       who-to-greet: Tanuj
    - name: Log Greeting time 
      run : echo "${{steps.hello-world-greet.outputs.time}}"
      
