name: Workflow Commands
on: [push]
jobs: 
    testing-wf-commands:
        runs-on: ubuntu-latest
        steps:
            - name: Setting an error message
              run: echo "::error::Missing Semicolon"
            - name: Print branch name
              run: echo "Branch:${GITHUB_REF#refs/heads/}"
            
            - name: Print SHA
              run: echo "SHA:${GITHUB_SHA}"
        
            - name: Print PR number
              run: echo "PR:${GITHUB_EVENT_NUMBER}"
